#!mast .ruby .yaropts bin lib spec test [A-Z].*
.ruby
bin/sourcery
lib/sourcery/caster.rb
lib/sourcery/cli.rb
lib/sourcery/context.rb
lib/sourcery/metadata.rb
lib/sourcery.rb
test/features/fixture/inline.rb
test/features/proofs/inline.rb
test/features/test_inline.rb
test/unit/fixture/inline.rb
test/unit/fixture/inline_complex.rb
test/unit/inline_test.rb
