#!/usr/bin/env ruby

name    "sourcery"
version "0.1.0"
title   "Sourcery"
summary "Write Ruby code in the astrological plane."

description "Sourcery puts a spell-casting layer between
the code you write and the code that ships. Using ERB
templating in this layer lets you wirte highly dynamic
meta-code."

authors [
  'Trans <transfire@gmail.com>',
]

requirements [
  'malt',
  'facets',
  'detroit (build)'
]

resources(
  'home' => 'https://github.com/rubyworks/sourcery',
  'code' => 'https://github.com/rubyworks/sourcery'
)

repositories(
  'upstream' => 'git://github.com/rubyworks/sourcery.git'
)

created '2009-07-15'

copyrights [
  '2009 Rubyworks (BSD-2-Clause)'
]

